# Generated by Django 4.2 on 2025-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='trainer_images')),
            ],
        ),
    ]
